FROM bitnami/spark:3.3

USER root
WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY main.py .

RUN chmod g+rwX /app

CMD ["spark-submit", "--master", "local[*]", "main.py"]