CREATE TABLE IF NOT EXISTS tomorrowio_data (
    record_id SERIAL PRIMARY KEY,
    time TIMESTAMP,
    cloudBase DOUBLE PRECISION,
    cloudCeiling DOUBLE PRECISION,
    cloudCover DOUBLE PRECISION,
    dewPoint DOUBLE PRECISION,
    freezingRainIntensity DOUBLE PRECISION,
    hailProbability DOUBLE PRECISION,
    hailSize DOUBLE PRECISION,
    humidity DOUBLE PRECISION,
    precipitationProbability DOUBLE PRECISION,
    pressureSeaLevel DOUBLE PRECISION,
    pressureSurfaceLevel DOUBLE PRECISION,
    rainIntensity DOUBLE PRECISION,
    sleetIntensity DOUBLE PRECISION,
    snowIntensity DOUBLE PRECISION,
    temperature DOUBLE PRECISION,
    temperatureApparent DOUBLE PRECISION,
    uvHealthConcern DOUBLE PRECISION,
    uvIndex DOUBLE PRECISION,
    visibility DOUBLE PRECISION,
    weatherCode DOUBLE PRECISION,
    windDirection DOUBLE PRECISION,
    windGust DOUBLE PRECISION,
    windSpeed DOUBLE PRECISION,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    location_name TEXT,
    location_type TEXT
);